### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by pedroalbanese** [joncampbell123/arj#1]
Hi,

What is the command to display help in this version?

Thanks in advance.

**Comment by joncampbell123** [comment]
ARJ will show all commands and switches if you run it without any command line arguments.

Just type "arj" by itself.

**Comment by pedroalbanese** [comment]
So my build is corrupted. When I try to compress I get: Bus error

**Comment by joncampbell123** [comment]
Remove the "upx --best" lines from GNUmakefile, make clean, make again

**Comment by pedroalbanese** [comment]
There's no lines containing UPX expression.. I'm building on Kali Linux, armel. Same error accurs on amd64 Debian as well

**Comment by pedroalbanese** [comment]
$ ./arj
ARJ32 v 3.10, Copyright (c) 1998-2004, ARJ Software Russia. [13 Dec 2020]

Segmentation fault (core dumped)
